<form action="user/change_email" method="post" role="form" class="form-horizontal">
	<div class="form-group">
		<div class="col-sm-2">
			<label for="inputRegEmail">Email:</label>				
		</div>
		<div class="col-sm-8">
			<input type="email" class="form-control" id="inputRegEmail" placeholder="Email" name="email">
		</div>
		<div class="col-sm-2">
			<button type="submit" class="btn btn-default btn-primary">Zmenit</button>				
		</div>
	</div>
</form>
<form action="user/change_nick" method="post" role="form" class="form-horizontal">
	<div class="form-group">
		<div class="col-sm-2">
			<label for="nick">Prezdivka:</label>				
		</div>
		<div class="col-sm-8">
			<input type="text" class="form-control" id="nick" placeholder="Nick" name="nick">				
		</div>
		<div class="col-sm-2">
			<button type="submit" class="btn btn-default btn-primary">Zmenit</button>				
		</div>
	</div>
</form>