<form action="user/change_email" method="post" role="form" class="form-horizontal">
	<div class="form-group">
		<div class="col-sm-2">
			<label for="inputRegEmail"><?= t('models.user.email') ?>:</label>
		</div>
		<div class="col-sm-8">
			<input type="email" class="form-control" id="inputRegEmail" placeholder="<?= t('models.user.email') ?>" name="email">
		</div>
		<div class="col-sm-2">
			<button type="submit" class="btn btn-default btn-primary"><?= t('btn.edit') ?></button>
		</div>
	</div>
</form>
<form action="user/change_nick" method="post" role="form" class="form-horizontal">
	<div class="form-group">
		<div class="col-sm-2">
			<label for="nick"><?= t('models.user.nick') ?>:</label>
		</div>
		<div class="col-sm-8">
			<input type="text" class="form-control" id="nick" placeholder="<?= t('models.user.nick') ?>" name="nick">
		</div>
		<div class="col-sm-2">
			<button type="submit" class="btn btn-default btn-primary"><?= t('btn.edit') ?></button>
		</div>
	</div>
</form>