<div class="tab-select <?= $multiple ? 'tab-multiselect' : 'tab-select-one' ?>">	
	<h3><?= $name ?></h3>
	<i class="fa fa-chevron-down control control-show"></i>
	<i class="fa fa-chevron-up control control-hide"></i>
	<? foreach ($options as $option): ?>
		<div class="tab-opend">
			<div class="tab-btn tab-active">
				<? if($multiple): ?>
					<input type="checkbox" name="<?= $name ?>['<?= $option['name'] ?>']"/>
				<? else: ?>
					<input type="radio" name="<?= $name ?>" value="<?= $option['name'] ?>" checked="<?= $option['selected'] ?>" />
				<? endif ?>
				<span class="text">
					<?= $option['display_name'] ?>
				</span>
				<i class="fa fa-check selected"></i>
				<? if($multiple): ?>
					<i class="fa fa-times unselected"></i>
				<? endif ?>
			</div>
		</div>
	<? endforeach ?>
	<div class="tab-closed">
	</div>
</div>