<div class="tab-select <?= $multiple ? 'tab-multiselect' : 'tab-select-one' ?>">	
	<h3><?= $display_name ?></h3>
	<i class="fa fa-chevron-down control control-show"></i>
	<i class="fa fa-chevron-up control control-hide"></i>
	<?php foreach ($options as $option): ?>
		<div class="tab-opend">
			<div class="tab-btn <?= $option['selected'] ? 'tab-active' : ''?>">
				<?php if($multiple): ?>
					<input type="checkbox" name="<?= $name ?>['<?= $option['name'] ?>']"  <?= $option['selected'] ? 'checked' : '' ?>/>
				<?php else: ?>
					<input type="radio" name="<?= $name ?>" value="<?= $option['name'] ?>" <?= $option['selected'] ? 'checked' : '' ?>/>
				<?php endif ?>
				<span class="text">
					<?= $option['display_name'] ?>
				</span>
				<i class="fa fa-check selected"></i>
				<?php if($multiple): ?>
					<i class="fa fa-times unselected"></i>
				<?php endif ?>
			</div>
		</div>
	<?php endforeach ?>
	<div class="tab-closed">
	</div>
</div>