<!DOCTYPE html>
<html>
	<head>
	    <meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
    	<meta name="description" content="">
    	<meta name="author" content="MarvinCZ">
		<title>Titulek</title>
		<link rel="stylesheet" type="text/css" href="assets/styles/bootstrap.min.css" />
		<link rel="stylesheet" type="text/css" href="assets/styles/style.css" />
		<script src="assets/scripts/jquery-1.11.3.js"></script>
		<script src="assets/scripts/bootstrap.min.js"></script>
		<script src="assets/scripts/app.js"></script>
	</head>
	<body>
		<?= $array ?><br/>
		<?= $test->getB() ?><br/>
		<?= includeFile("views/partial.phtml", array('test'=>'t')); ?>
	</body>
</html>