<div class="inner-box datetime_picker">
	<div class="pull-left"><label class="big-label" for="<?= $name ?>"><?= $display_name ?></label></div>
	<?php if(!$required): ?>
		<div class="pull-right clear_date"><i class="fa fa-trash"></i></div>
	<?php endif ?>
	<div class="clear"></div>
	<div class="row">
		<div class="col-xs-2">
			<div class="head">Den</div>
			<div class="day-up controll controll-up"><i class="fa fa-chevron-up"></i></div>
			<input type="number" value="<?= $day ?>" class="form-control day"/>
			<div class="day-down controll controll-down"><i class="fa fa-chevron-down"></i></div>
		</div>
		<div class="col-xs-2">
			<div class="head">Měsíc</div>
			<div class="month-up controll controll-up"><i class="fa fa-chevron-up"></i></div>
			<input type="number" value="<?= $month ?>" class="form-control month"/>
			<div class="month-down controll controll-down"><i class="fa fa-chevron-down"></i></div>
		</div>
		<div class="col-xs-3">
			<div class="head">Rok</div>
			<div class="year-up controll controll-up"><i class="fa fa-chevron-up"></i></div>
			<input type="number" value="<?= $year ?>" class="form-control year"/>
			<div class="year-down controll controll-down"><i class="fa fa-chevron-down"></i></div>
		</div>
		<div class="col-xs-2 pull-right">
			<div class="head">Minuta</div>
			<div class="minute-up controll controll-up"><i class="fa fa-chevron-up"></i></div>
			<input type="number" value="<?= $minute ?>" class="form-control minute"/>
			<div class="minute-down controll controll-down"><i class="fa fa-chevron-down"></i></div>
		</div>
		<div class="col-xs-2 pull-right">
			<div class="head">Hodina</div>
			<div class="hour-up controll controll-up"><i class="fa fa-chevron-up"></i></div>
			<input type="number" value="<?= $hour ?>" class="form-control hour"/>
			<div class="hour-down controll controll-down"><i class="fa fa-chevron-down"></i></div>
		</div>
	</div>
	<input class="datetime" type="hidden" name="<?= $name ?>" value="<?= $value ?>">
</div>