<div class="tab-select <?= $multiple ? 'tab-multiselect' : 'tab-select-one' ?>" data-required="<?= $required ? 'true' : 'false' ?>" <?= $on_change ? "data-onchange=$on_change" : "" ?>>
	<label for="<?= $name ?>"><?= $display_name ?></label>
	<i class="fa fa-chevron-down control control-show"></i>
	<i class="fa fa-chevron-up control control-hide"></i>
	<div class="tab-opend">
	<?php if($multiple): ?>
		<div class="btn-all">VŠE</div>
		<div class="btn-nothing">NIC</div>
		<div class="clear"></div>
	<?php endif ?>
	<?php foreach ($options as $option): ?>
		<div class="tab-btn <?= $option['selected'] ? 'tab-active' : ''?>">
			<?php if($multiple): ?>
				<input type="checkbox" name="<?= $name ?>[]" value="<?= $option['name'] ?>"  <?= $option['selected'] ? 'checked="checked"' : '' ?>/>
			<?php else: ?>
				<input type="radio" name="<?= $name ?>" value="<?= $option['name'] ?>" <?= $option['selected'] ? 'checked="checked"' : '' ?>/>
			<?php endif ?>
			<span class="text">
				<?= $option['display_name'] ?>
			</span>
			<i class="fa fa-check selected"></i>
			<?php if($multiple): ?>
				<i class="fa fa-times unselected"></i>
			<?php endif ?>
		</div>
	<?php endforeach ?>
	</div>
	<div class="tab-closed">
	</div>
</div>