<div class="page page-middle">
	<header class="header hidden-xs">
		<a href="/notes"><h1><?= t('app.name') ?></h1></a>
		<div class="header-right">
			<div class="header-btn-large show-login"><?= t('common.login') ?></div>
		</div>
	</header>
	<div class="header row text-center visible-xs">
		<h1><?= t('app.name') ?></h1>
		<div class="header-right">
			<div class="header-btn-large show-login"><?= t('common.login') ?></div>
		</div>
	</div>
	<div class="container">
		<div class="flashes">
			<?php includeFile("Views/flashes.phtml", $params) ?>
		</div>
		<div class="inner-box">
			<h2><?= t('.what_is_head') ?></h2>
			<?= t('.what_is_body') ?>
		</div>
		<div class="inner-box">
			<h2><?= t('.offer_head') ?></h2>
			<?= t('.offer_body') ?>
		</div>
	</div>
</div>
<div class="over"></div>
<div class="login">
	<div class="inner-box">
		<div>
			<div class="tabs clearfix">
				<div class="tab-4 tab" data-selected="true" data-part="part-login">
					<?= t('common.login') ?>
				</div>
				<div class="tab-4 tab" data-part="part-register">
					<?= t('common.register') ?>
				</div>
				<a href="<?= $fblogin ?>">
					<div class="tab-2 tab tab-facebook tab-social">
						<i class="fa fa-facebook-square"></i>
					</div>
				</a>
				<a href="<?= $glogin ?>">
					<div class="tab-2 tab tab-google tab-social">
						<i class="fa fa-google-plus"></i>
					</div>
				</a>
			</div>
			<div class="parts">
				<div class="part-login">
					<form action="login" method="post" class="form-horizontal logreg-form remote">
						<div class="col-md-8 col-md-push-2">
							<div class="error-common error-box"></div>
							<div class="form-group">
								<input type="text" class="form-control" id="inputNick" placeholder="<?= t('models.user.nick') ?>" name="user[nick]">
							</div>
							<div class="form-group">
								<input type="password" class="form-control" id="inputPassword" placeholder="<?= t('models.user.password') ?>" name="user[password]">
							</div>
							<div class="form-group">
								<button type="submit" class="btn btn-default btn-primary btn-block"><?= t('common.login') ?></button>
							</div>
						</div>
					</form>
				</div>
				<div class="part-register">
					<form action="register" method="post" class="form-horizontal logreg-form remote" novalidate>
						<div class="col-md-8 col-md-push-2">
							<div class="form-group">
								<input type="email" class="form-control" id="inputRegEmail" placeholder="<?= t('models.user.email') ?>" name="user[email]">
								<div class="error-email error-box"></div>
							</div>
							<div class="form-group">
								<input type="text" class="form-control" id="inputRegNick" placeholder="<?= t('models.user.nick') ?>" name="user[nick]">
								<div class="error-nick error-box"></div>
							</div>
							<div class="form-group">
								<input type="password" class="form-control" id="inputRegPassword" placeholder="<?= t('models.user.password') ?>" name="user[password]">
								<div class="error-password error-box"></div>
							</div>
							<div class="form-group">
								<input type="password" class="form-control" id="inputRegPassword2" placeholder="<?= t('models.user.password2') ?>" name="user[password2]">
								<div class="error-password2 error-box"></div>
							</div>
							<div class="form-group">
								<button type="submit" class="btn btn-default btn-primary btn-block"><?= t('common.register') ?></button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>