<div class="page page-middle">
	<header class="header hidden-xs">
		<a href="/notes"><h1>Tasker</h1></a>
		<div class="header-right">
			<div class="header-btn-large show-login">LOGIN</div>
		</div>
	</header>
	<div class="header row text-center visible-xs">
		<h1>Tasker</h1>
		<div class="header-right">
			<div class="header-btn-large show-login">LOGIN</div>
		</div>
	</div>
	<div class="container">
		<div class="flashes">
			<?php includeFile("Views/flashes.phtml", $params) ?>
		</div>
		<div class="inner-box">
			<h2>Co je to tasker</h2>
			<p>Tasker je sluzbou, ktera spravuje vase poznamky a umoynuje je mit na jednom miste a vzdy k dispozici.</p>
		</div>
		<div class="inner-box">
			<h2>Co nabizi</h2>
			<ul>
				<li>Spravovat ukoly</li>
				<li>Jednoduchou registraci (fb/g+)</li>
				<li>Kategorizaci ukolu</li>
				<li>Sdileni ukolu</li>
				<li>Diskuze u ukolu</li>
			</ul>
		</div>
	</div>
</div>
<div class="over"></div>
<div class="login">
	<div class="inner-box">
		<div>
			<div class="tabs clearfix">
				<div class="tab-4 tab" data-selected="true" data-part="part-login">
					Přihlášení
				</div>
				<div class="tab-4 tab" data-part="part-register">
					Registrace
				</div>
				<a href="<?= $fblogin ?>">
					<div class="tab-2 tab tab-facebook tab-social">
						<i class="fa fa-facebook-square"></i>
					</div>
				</a>
				<a href="<?= $glogin ?>">
					<div class="tab-2 tab tab-google tab-social">
						<i class="fa fa-google-plus"></i>
					</div>
				</a>
			</div>
			<div class="parts">
				<div class="part-login">
					<form action="login" method="post" class="form-horizontal logreg-form">
						<div class="col-md-8 col-md-push-2">
							<div class="form-group">
								<input type="text" class="form-control" id="inputNick" placeholder="Nick" name="user[nick]">
								<input type="password" class="form-control" id="inputPassword" placeholder="Password" name="user[password]">
							</div>
							<div class="form-group">
								<button type="submit" class="btn btn-default btn-primary btn-block">Přihlásit se</button>
							</div>
						</div>
					</form>
				</div>
				<div class="part-register">
					<form action="register" method="post" class="form-horizontal logreg-form">
						<div class="col-md-8 col-md-push-2">
							<div class="form-group">
								<input type="email" class="form-control" id="inputRegEmail" placeholder="Email" name="user[email]">
								<input type="text" class="form-control" id="inputRegNick" placeholder="Přezdívka" name="user[nick]">
								<input type="password" class="form-control" id="inputRegPassword" placeholder="Heslo" name="user[password]">
								<input type="password" class="form-control" id="inputRegPassword2" placeholder="Zopakujte heslo" name="user[password2]">
							</div>
							<div class="form-group">
								<button type="submit" class="btn btn-default btn-primary btn-block">Registrovat se</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>