<div class="page page-middle">
	<header class="header hidden-xs">
		<a href="/notes"><h1>Tasker</h1></a>
		<div class="header-right">
			<div class="header-btn-large show-login">LOGIN</div>
		</div>
	</header>
	<div class="header row text-center visible-xs">
		<h1>Tasker</h1>
	</div>
	<div class="container">
		<div class="inner-box">
			<h2>Co je to tasker</h2>
			<p>Tasker je sluzbou, ktera spravuje vase poznamky a umoynuje je mit na jednom miste a vzdy k dispozici.</p>
		</div>
		<div class="inner-box">
			<h2>Co nabizi</h2>
			<ul>
				<li>Spravovat ukoly</li>
				<li>Jednoduchou registraci (fb/g+)</li>
				<li>Kategorizaci ukolu</li>
				<li>Sdileni ukolu</li>
				<li>Diskuze u ukolu</li>
			</ul>
		</div>
	</div>
</div>
<div class="over"></div>
<div class="login">
	<div class="inner-box">
			<div>
				<div class="buttons clearfix">
					<div class="button-6 button" data-selected="true" data-part="part-login">
						LOGIN
					</div>
					<div class="button-6 button" data-part="part-register">
						REGISTER
					</div>
				</div>
				<div class="parts">
					<div class="part-login">
						<form action="login" method="post" class="form-horizontal">
							<div class="form-group">
								<label for="inputNick" class="col-sm-4 control-label">Nick</label>
								<div class="col-sm-8">
									<input type="text" class="form-control" id="inputNick" placeholder="Nick" name="user[nick]">
								</div>
							</div>
							<div class="form-group">
								<label for="inputPassword" class="col-sm-4 control-label">Password</label>
								<div class="col-sm-8">
									<input type="password" class="form-control" id="inputPassword" placeholder="Password" name="user[password]">
								</div>
							</div>
							<div class="form-group">
								<div class="col-sm-offset-4 col-sm-8">
									<div class="checkbox">
										<label>
											<input type="checkbox"> Remember me
										</label>
									</div>
								</div>
							</div>
							<div class="form-group">
								<div class="col-sm-offset-4 col-sm-8">
									<button type="submit" class="btn btn-default">Sign in</button>
								</div>
							</div>
						</form>
					</div>
					<div class="part-register">
						<form action="register" method="post" class="form-horizontal">
							<div class="form-group">
								<label for="inputRegEmail" class="col-sm-4 control-label">Email</label>
								<div class="col-sm-8">
									<input type="email" class="form-control" id="inputRegEmail" placeholder="Email" name="user[email]">
								</div>
							</div>
							<div class="form-group">
								<label for="inputRegNick" class="col-sm-4 control-label">Přezdívka</label>
								<div class="col-sm-8">
									<input type="text" class="form-control" id="inputRegNick" placeholder="Přezdívka" name="user[nick]">
								</div>
							</div>
							<div class="form-group">
								<label for="inputRegPassword" class="col-sm-4 control-label">Heslo</label>
								<div class="col-sm-8">
									<input type="password" class="form-control" id="inputRegPassword" placeholder="Heslo" name="user[password]">
								</div>
							</div>
							<div class="form-group">
								<label for="inputRegPassword2" class="col-sm-4 control-label">Zopakujte heslo</label>
								<div class="col-sm-8">
									<input type="password" class="form-control" id="inputRegPassword2" placeholder="Zopakujte heslo" name="user[password2]">
								</div>
							</div>
							<div class="form-group">
								<div class="col-sm-offset-4 col-sm-8">
									<button type="submit" class="btn btn-default">Registrovat</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
			<div>
				<p>Příhláse je možné také pomocí sociálních sítí</p>
				<div class="row">
					<div class="col-md-6">
						<div class="fb-login"></div>
					</div>
					<div class="col-md-6">
						<div class="google-login"></div>
					</div>
				</div>
			</div>
	</div>
</div>