<a href="<?= $user->getPath() ?>" class="nounderline">
	<div class="inner-box">
		<img src="<?= $user->getAvatarPath() ?>" class="menu-img">
		<div class="title"><?= $user->getDisplayName() ?></div>
	</div>
</a>
<div class="inner-box no-padding">
	<nav>
		<ul>
			<a href="<?= $user->getPath() ?>"><li>Profil</li></a>
			<a href="settings"><li>Nastavení</li></a>
			<a href="logout"><li>Odhlásit se</li></a>
		</ul>
	</nav>
</div>