<a href="<?= $user->getPath() ?>" class="nounderline">
	<div class="inner-box">
		<img src="<?= $user->getAvatarPath() ?>" class="menu-img">
		<div class="title"><?= $user->getDisplayName() ?></div>
	</div>
</a>
<div class="inner-box no-padding">
	<nav>
		<ul>
			<a href="<?= $user->getPath() ?>"><li><?= t('view._menu.profile') ?></li></a>
			<a href="settings"><li><?= t('view._menu.settings') ?></li></a>
			<a href="logout"><li><?= t('common.logout') ?></li></a>
		</ul>
	</nav>
</div>