<!DOCTYPE html>
<html>
	<head>
		<base href="/">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="MarvinCZ">
		<title><?= $params['title'] ?></title>
		<link rel="stylesheet" type="text/css" href="assets/styles/bootstrap.min.css" />
		<link rel="stylesheet" type="text/css" href="assets/styles/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="assets/styles/nouislider.min.css">
		<script src="assets/scripts/jquery-1.11.3.js"></script>
		<script src="assets/scripts/hammer.min.js"></script>
		<script src="assets/scripts/bootstrap.min.js"></script>
		<script src="assets/scripts/app.js"></script>
		<script src="assets/scripts/select.js"></script>
		<script src="assets/scripts/datetime_picker.js"></script>
		<script src="assets/scripts/nouislider.min.js"></script>
		<link rel="stylesheet" type="text/css" href="assets/styles/style.css" />
		<link rel="shortcut icon" type="image/png" href="/assets/images/favicon.png"/>
	</head>
	<body>
		<?php includeFile($inside, $params) ?>
	</body>
</html>