<form method="POST">
  <input type="hidden" name="note[id]" value="<?= $note->getId() ?>">
  <div class="form-group inner-box">
    <label for="title">Titulek:</label>
    <input type="text" class="form-control" id="title" name="note[title]" value="<?= $note->getTitle() ?>">
  </div>
  <div class="form-group">
    <div class="inner-box">
      <?= select("Ketegorie","category", false, $categories, false) ?>
    </div>
  </div>
  <div class="form-group">
    <?= datetime_picker('Termín', 'note[deadline]', false, array('value' => $note->getDeadline())) ?>
  </div>
  <div class="form-group inner-box">
    <label for="description">Popis:</label>
    <input type="text" class="form-control" id="description" name="note[description]"  value="<?= $note->getDescription() ?>">
  </div>
  <div class="inner-box">
    <?= select("Stav","note[state]", false, stateOptions($note->getState()), true) ?>
  </div>
  <input type="submit" value="Uložit" class="btn btn-primary btn-full">
</form>