<div class="col-xxs-12 col-xs-6 col-sm-4 col-md-3 col-xl-2 note-container">
	<a href="notes/<?= $note->getId() ?>" class="nounderline">
		<div class="note">
			<div class="title"><?= $note->getTitle() ?></div>
			<div class="info <?= $note->getCategory() ? "category-".$note->getCategory()->getColor() : "" ?>">
				<?= $note->getCategory() ? $note->getCategory()->getName() : t('.no_category') ?>
				<?php if($note->getDeadline()): ?>
					<div class="pull-right deadline">
						<span title="<?= t('models.note.deadline') ?>"><i class="fa fa-clock-o"></i> <?= $note->getFormatedDeadline() ?></span>
					</div>
				<?php endif ?>	
			</div>
			<div class="note-status note-status-<?= $note->getStateClass() ?>">
				<?= $note->getStateText() ?>
			</div>
		</div>
	</a>
</div>