<div class="row side-padding share-form">
	<div class="show-info">
		<div class="pull-left">
			<a href="<?= $target_link ?>" class="user-link"><?= $name ?></a>
		</div>
		<div class="pull-right">
			<?= $rights ?>
			<div class="btn btn-primary edit-share">
				<i class="fa fa-pencil"></i>
			</div>
			<a href="share/remove/<?= $id ?>">
				<div class="btn btn-danger">
					<i class="fa fa-trash"></i>
				</div>
			</a>
		</div>
	</div>
	<div class="form">
		<div class="pull-left">
			<a href="<?= $target_link ?>" class="user-link"><?= $name ?></a>
		</div>
		<div class="pull-right">
			<form action="<?= $form_link ?>" method="POST">
				<select name="share_rights">
					<?= $options ?>
				</select>
				<input type="submit" class="btn btn-primary" value="edit">
			</form>
		</div>		
	</div>
</div>