<form method="POST" action="notes/create">
  <div class="form-group">
    <label for="title">Title:</label>
    <input type="text" class="form-control" id="title" name="note[title]">
  </div>
  <div class="form-group">
    <?= select("Category","category", false, $categories) ?>
  </div>
  <div class="form-group">
    <label for="description">Description:</label>
    <input type="text" class="form-control" id="description" name="note[description]">
  </div>
  <input type="submit" value="Submit" class="btn btn-default">
</form>