<div class="page page-middle">
	<header class="header hidden-xs">
		<a href="/notes"><h1>Note - <?= $note->getTitle() ?></h1></a>
		<div class="header-right">
			<?php if($rights >= 1): ?>
				<div class="header-btn-large pull-left"><a href="<?= $note->getEditPath() ?>"><i class="fa fa-pencil"></i></a></div>
			<?php endif ?>
			<?php if($rights >= 2): ?>
				<div class="header-btn-large show-share pull-left"><i class="fa fa-share-alt"></i></div>
			<?php endif ?>
			<span class="user-name"><?= $user->getNick() ?></span>
			<img src="<?= $user->getAvatarPath() ?>" class="header-img img-circle">
		</div>
	</header>
	<div class="header row text-center visible-xs">
		<div class="header-btn pull-left"><a href="/notes"><i class="fa fa-home"></i></a></div>
		Note
		<div class="header-btn page-show-right pull-right"><i class="fa fa-share-alt"></i></div>
		<?php if($rights >= 1): ?>
			<div class="header-btn pull-right"><a href="<?= $note->getEditPath() ?>"><i class="fa fa-pencil"></i></a></div>
		<?php endif ?>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<div class="inner-box visible-xs">
					<h3><?= $note->getTitle() ?></h3>
				</div>
				<?php if(!empty($note->getDescription())): ?>
					<div class="inner-box">
						<h3>Description</h3>
						<?= $note->getDescription() ?>
					</div>
				<?php endif ?>
				<?php if($note->getCategoryId()): ?>
					<a href="<?= $note->getCategory()->getShowPath() ?>">
						<div class="inner-box">
							<h3>Category</h3>
							<?= $note->getCategory()->getName() ?>
							<div class="cat-stripe cat-stripe-<?= $note->getCategory()->getColor() ?>" title="<?= $note->getCategory()->getName() ?>"></div>
						</div>
					</a>
				<?php endif ?>
				<?php if($note->getDeadline()): ?>
				<div class="inner-box" id="deadline">
					<h3>DeadLine</h3>
					<?= $note->getDeadline()->format('d. m. Y  H:i') ?>
					<div class="pull-right countdown" data-to="<?= $note->getDeadline()->format('d.m.Y.H.i') ?>"></div>
				</div>
				<?php endif ?>
				<div class="inner-box" id="comments">
					<h3>Comments</h3>
					<div class="comments">
						<?php foreach ($note->getComments() as $c): ?>
							<?php includeFile("Views/Note/_comment.phtml", array('comment' => $c)) ?>
						<?php endforeach ?>
						<?php if($note->getComments()->count() == 0): ?>
							<p>Jste to nikdo nekomentoval. Budte prvni.</p>
						<?php endif ?>
					</div>
					<div class="input-group">
						<input type="text" name="comment-message" class="form-control">
						<span class="input-group-btn">
							<button class="btn btn-primary sent-message" type="button" data-note="<?= $note->getId() ?>">Odeslat</button>
						</span>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="select-state">
				<?php if($rights >= 1): ?>
					<?= select("State","state", false, $states, true, 'note/'.$note->getId().'/state/') ?>
				<?php else: ?>
					<div class="inner-box">
						<h3>State</h3>
						<?= $note->getState() ?>
					</div>
				<?php endif ?>
				</div>
				<div class="inner-box" id="shared-with">
					<h3>Sdileno s</h3>
					<?php foreach ($shared_to as $shared): ?>
						<div class="row side-padding">
							<?= sharedToHTML($shared) ?>
						</div>
					<?php endforeach ?>
					<?php if(empty($shared_to)): ?>
						<div class="row side-padding">
							Tento úkol máte k dispozici jen vy. Pokud chcete sdílet přístup klikněte na <i class="fa fa-share-alt"></i>
						</div>
					<?php endif ?>
				</div>
				<div class="inner-box">
					<h3>Files</h3>
					<div class="file">
						<i class="fa fa-paperclip"></i>
						photo.jpeg
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="inner-box no-padding user-menu">
		<nav>
			<ul>
			<a href="<?= $user->getPath() ?>"><li>PROFILE</li></a>
				<a href="options"><li>OPTIONS</li></a>
				<a href="logout"><li>LOG OUT</li></a>
			</ul>
		</nav>
	</div>
</div>
<?php if($rights >= 2): ?>
	<div class="page page-right">
		<div class="header row text-center">
			<div class="header-btn page-show-middle pull-left visible-xs"><i class="fa fa-reply"></i></div>
			<div class="header-btn page-hide-right pull-left hidden-xs"><i class="fa fa-reply"></i></div>
			Share
		</div>
		<div class="container">
			<div class="inner-box">
				<h3>Existující sdílení:</h3>
				<?php foreach ($shared_to as $shared): ?>
					<?php if($shared['what_type'] == "note"): ?>
						<?= sharedToForm($shared, $rights) ?>
					<?php endif ?>
				<?php endforeach ?>
			</div>
			<div class="inner-box">
				<h3>Přidat uživatele</h3>
				<form action="share/add/note/<?= $note->getId() ?>" method="POST">
						<div class="pull-left">
							<input name="name" class="form-control complete-user">
						</div>
						<div class="pull-right">
							<select name="share_rights">
								<?= shareOptionsForSelect(null, $rights) ?>
							</select>
							<input type="submit" class="btn btn-primary" value="add">
						</div>
				</form>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
<?php endif ?>
<div class="over"></div>