<div class="page page-left">
	<div class="header row text-center">
		Menu
		<div class="header-btn page-show-middle pull-right"><i class="fa fa-home"></i></div>
	</div>
	<div class="container">
		<a href="<?= $user->getPath() ?>" class="nounderline">
			<div class="inner-box">
				<img src="<?= $user->getAvatarPath() ?>" class="menu-img">
				<div class="title"><?= $user->getDisplayName() ?></div>
			</div>
		</a>
		<div class="inner-box no-padding">
			<nav>
				<ul>
					<a href="options"><li>OPTIONS</li></a>
					<a href="logout"><li>LOG OUT</li></a>
				</ul>
			</nav>
		</div>
		<div class="inner-box no-side-padding">
			<h3>Notifications</h3>
			<?php foreach ($notifications as $notification): ?>
				<a href="<?= $notification->getLink() ?>">
					<div class="notification">
						<?= $notification->getIcon() ?><div class="text"><?= $notification->getText() ?></div>
					</div>
				</a>
			<?php endforeach ?>
		</div>
	</div>
</div>
<div class="page page-middle">
	<header class="header hidden-xs">
		<a href="/notes"><h1>Ůkoly</h1></a>
		<div class="header-right">
			<a href="/notes/add">
				<div class="header-btn-large pull-left"><i class="fa fa-plus"></i></div>
			</a>
			<div class="header-btn-large show-filter pull-left"><i class="fa fa-search"></i></div>
			<span class="user-name"><?= $user->getNick() ?></span>
			<img src="<?= $user->getAvatarPath() ?>" class="header-img img-circle">
		</div>
	</header>
	<div class="header row text-center visible-xs">
		<div class="header-btn page-show-left pull-left"><i class="fa fa-bars"></i></div>
		Ůkoly
		<div class="header-btn page-show-right pull-right"><i class="fa fa-search"></i></div>
	</div>
	<div class="container container-lg-large">
		<div class="flashes">
			<?php includeFile("Views/flashes.phtml", $params) ?>
		</div>
		<div class="row notes">
			<div class="col-xxs-12 col-xs-6 visible-xs note-container">
				<a href="/notes/add">
					<div class="note new-note">
						<i class="fa fa-plus-circle"></i>
					</div>
				</a>
			</div>
			<?php foreach ($notes as $note): ?>
				<?php includeFile("Views/Note/_note.phtml",array('note' => $note)) ?>
			<?php endforeach ?>
			<?php if(!$notes->isLastPage()): ?>
				<div class="next_page inner-box load-more" data-nextpage="<?= $notes->getNextPage() ?>">LOAD MORE</div>
			<?php endif ?>
		</div>
	</div>
	<div class="inner-box no-padding user-menu">
		<nav>
			<ul>
			<a href="<?= $user->getPath() ?>"><li>PROFIL</li></a>
				<a href="options"><li>NASTAVENÍ</li></a>
				<a href="logout"><li>ODHLÁSIT</li></a>
			</ul>
		</nav>
	</div>
</div>
<div class="page page-right">
	<div class="header row text-center">
		<div class="header-btn page-show-middle pull-left visible-xs"><i class="fa fa-home"></i></div>
		<div class="header-btn page-hide-right pull-left hidden-xs"><i class="fa fa-reply"></i></div>
		Filtr
	</div>
	<div class="container btn-down">
		<form class="search-form">
			<div class="inner-box">
				<label for="fulltext">Fulltextové vyhledávaní</label>
				<div class="input-group">
					<input type="text" class="form-control" name="fulltext" value="<?= $fulltext ?>">
					<span class="input-group-addon clear-input"><i class="fa fa-trash"></i></span>
				</div>
			</div>
			<?= datetime_picker('Termín do', 'deadline_to', false, array('value' => $deadline_to)) ?>
			<div class="inner-box">
				<label for="importance_from">Důležitost od</label>
				<div class="row">
					<div class="col-xs-8">
						<div id="importance-from"></div>
					</div>
					<div class="col-xs-4">
						<input type="text" class="form-control" id="importance-from-field" name="importance_from" readonly="readonly" value="<?= $importance ?>">
					</div>
				</div>
			</div>
			<?= select("Kategorie","category", true, $categories, false) ?>
			<div class="filter_submit container-width">
				<input type="submit" value="Search" class="big-btn"/>
			</div>
			<?= select("Stav","state", true, $states, false) ?>
			<?= select("Seřadit dle","sort_by", false, $sort_by, true) ?>
			<?= select("Vztah","relation", false, $relation, true) ?>
		</form>
	</div>
</div>
<div class="over"></div>