<div class="page page-left">
	<div class="header row text-center">
		Menu
		<div class="header-btn page-show-middle pull-right"><i class="fa fa-chevron-right"></i></div>
	</div>
	<div class="inner">blablabla</div>
</div>
<div class="page page-middle">
	<div class="header row text-center">
		<div class="header-btn page-show-left pull-left"><i class="fa fa-chevron-left"></i></div>
		Notes
		<div class="header-btn page-show-right pull-right"><i class="fa fa-chevron-right"></i></div>
	</div>
	<div class="inner-btn">Add Note</div>
</div>
<div class="page page-right">
	<div class="header row text-center">
		<div class="header-btn page-show-middle pull-left"><i class="fa fa-chevron-left"></i></div>
		Filter
	</div>
	<div class="inner">blablabla</div>
</div>