<div class="page page-left">
	<div class="header row text-center">
		Menu
		<div class="header-btn page-show-middle pull-right"><i class="fa fa-chevron-right"></i></div>
	</div>
	<div class="inner">blablabla</div>
</div>
<div class="page page-middle">
	<header class="header hidden-xs">
		<h1>Hlavicka</h1>
		<div class="header-right">
			<span class="user-name"><?= $user->getNick() ?></span>
			<img src="<?= $user->getAvatarPath() ?>" class="header-img">
		</div>
	</header>
	<div class="header row text-center visible-xs">
		<div class="header-btn page-show-left pull-left"><i class="fa fa-chevron-left"></i></div>
		Notes
		<div class="header-btn page-show-right pull-right"><i class="fa fa-chevron-right"></i></div>
	</div>
	<div class="container">
		<div class="row notes">
			<?php foreach ($notes as $note): ?>
				<?php includeFile("Views/Note/_note.phtml",array('note' => $note)) ?>
			<?php endforeach ?>
		</div>
	</div>
</div>
<div class="page page-right">
	<div class="header row text-center">
		<div class="header-btn page-show-middle pull-left"><i class="fa fa-chevron-left"></i></div>
		Filter
	</div>
	<div class="inner">blablabla</div>
</div>