<form method="POST">
  <div class="form-group">
    <label for="email">Email address:</label>
    <input type="email" class="form-control" id="email" name="user[email]">
  </div>
  <div>
    <label for="nick">Nick:</label>
    <input type="nick" class="form-control" id="nick" name="user[nick]">
  </div>
  <div class="form-group">
    <label for="pwd">Password:</label>
    <input type="password" class="form-control" id="pwd" name="user[password]">
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>